version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes: [ "mongo_data:/data/db" ]

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: chronos
      RABBITMQ_DEFAULT_PASS: chronos
      RABBITMQ_DEFAULT_VHOST: chronos

  redis:
    image: redis:7
    restart: unless-stopped
    ports: ["6379:6379"]
    command: ["redis-server", "--appendonly", "yes"]

  # worker:
  #   build:
  #     context: ../..
  #     dockerfile: deploy/docker/Dockerfile.worker
  #   restart: unless-stopped
  #   env_file:
  #     - ../../.env
  #   environment:
  #     MONGO_URI: ${MONGO_URI:-mongodb://mongo:27017/chronos}
  #     BROKER_URL: ${BROKER_URL:-amqp://chronos:chronos@rabbitmq:5672/chronos}
  #     RESULT_BACKEND: ${RESULT_BACKEND:-redis://redis:6379/0}
  #   depends_on: [mongo, rabbitmq, redis]

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on: [loki]

  grafana:
    image: grafana/grafana:10.3.1
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on: [loki]

  api:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.api
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      MONGO_URI: ${MONGO_URI:-mongodb://mongo:27017/chronos}
      BROKER_URL: ${BROKER_URL:-amqp://chronos:chronos@rabbitmq:5672/chronos}
      RESULT_BACKEND: ${RESULT_BACKEND:-redis://redis:6379/0}
      APP_NAME: ${APP_NAME:-chronos-ge}
      APP_VERSION: ${APP_VERSION:-0.1.0}
      API_PORT: ${API_PORT:-8000}
      GIT_COMMIT: ${GIT_COMMIT:-unknown}
      BUILD_TIME: ${BUILD_TIME:-unknown}
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    depends_on: [ mongo, rabbitmq, redis ]

volumes:
  mongo_data:
